### ISSUE TITLE
Training AUC "-nan" issues and a question about federated learning. 

### ISSUE THREAD

**Issue by lovelynewlife** [FedTree/ECNU-FedTree-Challenge#1]
Hello，
first, thank you for this great work！
There are two questions I am curious about. Thanks a lot if you are willing to answer for me.
1. when I was trainging model using p3.conf-p6.conf, the AUC during training is always "-nan", but the final evaluations are just fine. Is this a problem with my files or a feature of federated learning?
example config:
data=./data/creditcard3/0.csv,./data/creditcard3/1.csv,./data/creditcard3/2.csv,./data/creditcard3/3.csv,./data/creditcard3/4.csv,./data/creditcard3/5.csv,./data/creditcard3/6.csv,./data/creditcard3/7.csv,./data/creditcard3/8.csv,./data/creditcard3/9.csv
test_data=./data/creditcard_test.csv
n_parties=10
num_class=2
mode=horizontal
objective=binary:logistic
data_format=csv
privacy_tech=none
model_path=fedtree.model
max_num_bin=16
learning_rate=0.1
max_
depth=6
n_trees=10
![1](https://user-images.githubusercontent.com/46183740/208654061-6db6b8c3-ddf4-458f-a2ef-78b8258ab52c.PNG)

2. I am just curious that is feature engineering the same for every institution in federated learning? since in general machine learning, users usually apply a specific feature engineering on a dataset. If not, how will it affect the training process and results of the training? Or, is there any works about feature engineering in federated learning you can recommend to me?

Best regards.

**Comment by QinbinLi** [comment]
Hi @lovelynewlife ,

1. Thanks for your feedback! It's a bug of FedTree. I have fixed it in the latest version. You may pull it and re-compile FedTree. The final AUC is not affected.

2. The feature engineering may not be the same for every institution. In this challenge, the basic requirement is to tune the training parameters, which is also required in centralized machine learning. Federated learning brings more flexibility to feature engineering. You are allowed to do any feature engineering you want as long as each institution does not access the data of other institutions. Also, you have additional parameters to tune such as the number of parties. However, you need to ensure that federated learning can successfully run, e.g., FedTree may not successfully run if each institution has a different number of features of the processed local dataset.  

Sorry that I do not know any works about feature engineering for the local datasets in federated learning. In research papers, we usually assume that the institutions have already processed the data. We usually only tune the training parameters.
